/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.1.6' (BDS version 1.0.1531.0) */

#include "ble_ios.h"
#include <string.h>
#include "nordic_common.h"
#include "ble_srv_common.h"
#include "app_util.h"
#include "app_util_bds.h"

#define OPCODE_LENGTH 1 /**< Length of opcode inside ios packet. */
#define HANDLE_LENGTH 2 /**< Length of handle inside ios packet. */

/* TODO Consider changing the max values if encoded data for characteristic/descriptor is fixed length */ 
#define MAX_INPUT_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted input. */ 
#define MAX_OUTPUT_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted output. */ 

/**@brief Function for encoding input.
 *
 * @param[in]   p_input              input characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t input_encode(ble_ios_input_t * p_input, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    encoded_buffer[len++] = p_input->value;
    return len;
}

/**@brief Function for decoding input.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
static uint8_t input_decode(uint8_t data_len, uint8_t * p_data, ble_ios_input_t * p_write_val)
{
    uint8_t pos = 0;
    p_write_val->value = p_data[pos++]; 

    return pos;
} 
/**@brief Function for encoding output.
 *
 * @param[in]   p_output              output characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t output_encode(ble_ios_output_t * p_output, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    encoded_buffer[len++] = p_output->value;
    return len;
}


/**@brief Function for handling the Connect event.
 *
 * @param[in]   p_ios       ios Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_connect(ble_ios_t * p_ios, ble_evt_t * p_ble_evt)
{
    p_ios->conn_handle = p_ble_evt->evt.gap_evt.conn_handle;
}

/**@brief Function for handling the Disconnect event.
 *
 * @param[in]   p_ios       ios Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_disconnect(ble_ios_t * p_ios, ble_evt_t * p_ble_evt)
{
    UNUSED_PARAMETER(p_ble_evt);
    p_ios->conn_handle = BLE_CONN_HANDLE_INVALID;
}

/**@brief Function for handling the Write event.
 *
 * @param[in]   p_ios       ios Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_write(ble_ios_t * p_ios, ble_gatts_evt_write_t * p_ble_evt)
{
    
    if(p_ble_evt->handle == p_ios->input_handles.value_handle)
    {
        if(p_ios->evt_handler != NULL)
        {
            ble_ios_evt_t evt;
            evt.evt_type = BLE_IOS_INPUT_EVT_WRITE;
            input_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.input);
            p_ios->evt_handler(p_ios, &evt);
        }
    }
    if(p_ble_evt->handle == p_ios->output_handles.cccd_handle)
    {
        if(p_ios->evt_handler != NULL)
        {
            ble_ios_evt_t evt;
            evt.evt_type = BLE_IOS_OUTPUT_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_ios->evt_handler(p_ios, &evt);
        }
    } 
}

/**@brief Authorize WRITE request event handler.
 *
 * @details Handles WRITE events from the BLE stack.
 *
 * @param[in]   p_sc_ctrlpt  SC Ctrlpt structure.
 * @param[in]   p_gatts_evt  GATTS Event received from the BLE stack.
 *
 */
static void on_rw_authorize_request(ble_ios_t * p_ios, ble_gatts_evt_t * p_gatts_evt)
{
    ble_gatts_evt_rw_authorize_request_t * p_auth_req = &p_gatts_evt->params.authorize_request;
    if (p_auth_req->type == BLE_GATTS_AUTHORIZE_TYPE_WRITE)
    {
        if (   (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_PREP_WRITE_REQ)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_NOW)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_CANCEL)
           )
        {
        
        }
    }
}

/**@brief Function for handling BLE events.
 *
 * @param[in]   p_ios       ios Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
void ble_ios_on_ble_evt(ble_ios_t * p_ios, ble_evt_t * p_ble_evt)
{
    switch (p_ble_evt->header.evt_id)
    {
        case BLE_GAP_EVT_CONNECTED:
            on_connect(p_ios, p_ble_evt);
            break;
        case BLE_GAP_EVT_DISCONNECTED:
            on_disconnect(p_ios, p_ble_evt);
            break;
        case BLE_GATTS_EVT_WRITE:
            on_write(p_ios, &p_ble_evt->evt.gatts_evt.params.write);
            break;
         case BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST:
            on_rw_authorize_request(p_ios, &p_ble_evt->evt.gatts_evt);
            break;
        default:
            //No implementation needed.
            break;
    }
}

/**@brief Function for initializing the ios. */
uint32_t ble_ios_init(ble_ios_t * p_ios, const ble_ios_init_t * p_ios_init)
{
    uint32_t err_code;
    ble_uuid_t ble_uuid;

    // Initialize service structure
    p_ios->evt_handler = p_ios_init->evt_handler;
    p_ios->conn_handle = BLE_CONN_HANDLE_INVALID;
    
    // Add a custom base UUID.
    ble_uuid128_t bds_base_uuid = {{0xD7, 0xCC, 0xA8, 0xD7, 0xDD, 0x1A, 0x6C, 0x93, 0x21, 0x43, 0x41, 0x65, 0x00, 0x00, 0xF2, 0x70}};
    uint8_t       uuid_type;
    err_code = sd_ble_uuid_vs_add(&bds_base_uuid, &uuid_type);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    }
    ble_uuid.type = uuid_type;
    ble_uuid.uuid = 0x6C9C;
        
    // Add service
    err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY, &ble_uuid, &p_ios->service_handle);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add input characteristic
    ble_ios_input_t input_initial_value = p_ios_init->ble_ios_input_initial_value; 

    uint8_t input_encoded_value[MAX_INPUT_LEN];
    ble_add_char_params_t add_input_params;
    memset(&add_input_params, 0, sizeof(add_input_params));
    
    add_input_params.uuid                = 0xFBC6; 
    add_input_params.max_len             = MAX_INPUT_LEN;
    add_input_params.init_len            = input_encode(&input_initial_value, input_encoded_value);
    add_input_params.p_init_value        = input_encoded_value; 
    add_input_params.char_props.write_wo_resp    = 1; 
    add_input_params.write_access        = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_input_params.is_var_len          = 1; 

    err_code = characteristic_add(p_ios->service_handle, &add_input_params, &(p_ios->input_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add output characteristic
    ble_ios_output_t output_initial_value = p_ios_init->ble_ios_output_initial_value; 

    uint8_t output_encoded_value[MAX_OUTPUT_LEN];
    ble_add_char_params_t add_output_params;
    memset(&add_output_params, 0, sizeof(add_output_params));
    
    add_output_params.uuid                = 0x50B8; 
    add_output_params.max_len             = MAX_OUTPUT_LEN;
    add_output_params.init_len            = output_encode(&output_initial_value, output_encoded_value);
    add_output_params.p_init_value        = output_encoded_value; 
    add_output_params.char_props.notify   = 1; 
    add_output_params.char_props.read     = 1; 
    add_output_params.read_access         = SEC_OPEN; 
    add_output_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_output_params.is_var_len          = 1; 

    err_code = characteristic_add(p_ios->service_handle, &add_output_params, &(p_ios->output_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for setting the output. */
uint32_t ble_ios_output_set(ble_ios_t * p_ios, ble_ios_output_t * p_output)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_OUTPUT_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = output_encode(p_output, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_ios->conn_handle, p_ios->output_handles.value_handle, &gatts_value);
}

/**@brief Function for sending the output. */
uint32_t ble_ios_output_send(ble_ios_t * p_ios, ble_ios_output_t * p_output)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_ios->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_OUTPUT_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = output_encode(p_output, encoded_value);
        hvx_params.handle = p_ios->output_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_ios->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

